2020-06-03 15:27:46,604 - log_output.py[line:32] - ERROR: 用例用户名长度校验执行成功！
NoneType: None
